### ISSUE TITLE
deprecation warning: Mojo::File::spurt is deprecated in favor of Mojo::File::spew

### ISSUE THREAD

**Issue by niceperl** [mojolicious/mojo-assetpack#152]
* Mojolicious::Plugin::AssetPack version: 2.14
* Perl version: 5.36.0
* Operating system: Linux 

### Steps to reproduce the behavior
Running the plugin shows a deprecation warning in console
Mojolicious version: 9.37

### Expected behavior
No deprecation warnings

### Actual behavior
```
Mojo::File::spurt is deprecated in favor of Mojo::File::spew at /(...)/Mojo/Util.pm line 126.
Mojo::Util::deprecated("Mojo::File::spurt is deprecated in favor of Mojo::File::spew") called at /(...)/Mojo/File.pm line 151
Mojo::File::spurt(Mojo::File=SCALAR(...), ... called at /(...)/perl5/Mojolicious/Plugin/AssetPack/Store.pm line 291
```

**Comment by nicomen** [comment]
Seems that no changes will pass tests until this is merged. There are issues with old perl images and with perltidy changed slightly. 

I'm not sure if I'm allowed to merge in those to the mainline, but can do it if I get a go ahead.

https://github.com/mojolicious/mojo-assetpack/pull/153
